### ISSUE TITLE
fetch_conf_desc: too short response: actual length:9

### ISSUE THREAD

**Issue by cantops** [cezanne/usbip-win#109]
When attaching individual USB devices, the prompt is as follows:

fetch_conf_desc: too short response: actual length:9

source:usbip_wudev.c 
line:49

Have you ever met? It looks like descriptor error. Should we start from the server or the client?

**Comment by cezanne** [comment]
@cantops : Never met except while developing a forwarding routine. More detailed descriptions are required such as logs. Log generation methods are described in [README.md](https://github.com/cezanne/usbip-win#reporting-bug).

**Comment by cezanne** [comment]
@cantops : I'm going to close the issue. Please reopen if you need.
