### ISSUE TITLE
Microchip chip device tool programmer

### ISSUE THREAD

**Issue by kmvi-dev** [cezanne/usbip-win#111]
When using the latest version of USBIP windows client, the following problem was discovered:
   When forwarding a USB chip programming device manufactured by Microchip Technology Inc, in particular, the Atmell-ICE programmer (this is the programmer debugger), or, for example, AVRISp-MKII (just the programmer), MPLAB ICD 3 In-Circuit Debugger and IDE that use these tools , work with the WinUsb driver. When forwarding using the usbip client on Windows and the usbip server on ubuntu 18.04 and kernel version 5.3.0.42, device drivers are loaded, but the programming environment does not detect remote devices on the bus.
In the screenshots:

IDE, on which both local access and forwarding of the USBIP chip programmig device was checked.
![AtmellStudio](https://user-images.githubusercontent.com/48018001/76080624-f276aa00-5faf-11ea-908f-988d7bd50de2.png)
![AtmellStudio-2](https://user-images.githubusercontent.com/48018001/76080835-79c41d80-5fb0-11ea-97b1-30348301a1d7.png)

UsbLocalConnect.png - local connection to the chip programming device (without using USBIP).
![UsbLocalConnect](https://user-images.githubusercontent.com/48018001/76080691-1c2fd100-5fb0-11ea-9a63-beb2b1c76c47.png)

Then the USBIP driver was installed:
![1](https://user-images.githubusercontent.com/48018001/76080711-2d78dd80-5fb0-11ea-8b7a-a7eb37aa8aae.png)

and the result of the device forwarding using the USBIP driver and app:
![USBIPRemoteConnect](https://user-images.githubusercontent.com/48018001/76081126-22727d00-5fb1-11ea-83c5-b3d915323991.png)

A similar problem manifests itself in the MPLAB X IDE (v5.10)

**Comment by cezanne** [comment]
@kmvi-dev :
> When using the latest version of USBIP windows client, the following problem was discovered:

Old versions also had the problem, didn't it?

There's remarkably different two things in your screenshots: Device name and instance id. But capitalization of instance id would not matter because the vendor id and the product id were well detected. So how about enforcing the device name to "Atmel-ICE CMSIS-DAP" from "on USB/IP VHCI"?

The string to be modified is here:
https://github.com/cezanne/usbip-win/blob/bcf3afaff05478548b8d47f03b23406cd391c38b/driver/vhci/vhci_vpdo.c#L17

**Comment by iv-dev** [comment]
> Old versions also had the problem, didn't it?
Yes.

> There's remarkably different two things in your screenshots: Device name and instance id. But capitalization of instance id would not matter because the vendor id and the product id were well detected. So how about enforcing the device name to "Atmel-ICE CMSIS-DAP" from "on USB/IP VHCI"?

Ок.

**Comment by koudis** [comment]
I had simillar problem. My programmer must be atrached to native Windows USB HUB otherwise it does not work. (I had problem even with comercial solutions if I choose "attach devices to separate device hub")

**Comment by iv-dev** [comment]
I think the problem lies in the usb / ip configuration. Missing value in the Power field. This can be seen in the last screenshot.
When a programming device is loaded into the driver stack, the WinUsb.sys driver is also loaded. Our problem, I think, somehow intersects with # 105

**Comment by cezanne** [comment]
@kmvi-dev : Can you share USB packet logs of directly attached your device(without usbip-win). One of such a tool is [USBPcap](https://desowin.org/usbpcap/).

**Comment by VdIlyaIv** [comment]
Yes, I will make such a log. Can I use the UsbSnoop tool?

**Comment by kmvi-dev** [comment]
Yes, I will make such a log. Can I use the UsbSnoop tool?
https://github.com/SnoopWare/usbsnoop

**Comment by cezanne** [comment]
@kmvi-dev : I recommend USBPcap because I should learn usbsnoop. 😄 I have used Wireshark to examine USB captured logs and USBPcap supports wireshark format.

**Comment by kmvi-dev** [comment]
Ok . Now I will make  a log with USBCap. But first I will say that the difference in the sequence and contents of URB packets between the local connection and the connection using usbip is significant. I checked URB with USBSnoop

**Comment by kmvi-dev** [comment]
the log file is ready,
[AvrMKII.zip](https://github.com/cezanne/usbip-win/files/4562908/AvrMKII.zip)

**Comment by cezanne** [comment]
@kmvi-dev : Driver file please..

**Comment by kmvi-dev** [comment]
Drivers are shipped with the Atmel studio 7.0 distributive. But I can send you a folder with these drivers
[Drivers.zip](https://github.com/cezanne/usbip-win/files/4564044/Drivers.zip)

**Comment by cezanne** [comment]
@kmvi-dev : many infs.. Which one should be installed?

**Comment by kmvi-dev** [comment]
I install the microcontroller programming environment and drivers from the distribution
https://www.microchip.com/mplab/avr-support/avr-and-sam-downloads-archive
during installation, the driver installation program is called, which programmers need to work with the programming device, for example, with the AVRISP-MKII device

**Comment by kmvi-dev** [comment]
@cezanne 
you can try to run the DPInst.exe module with administrator rights, which is located in the archive along the path Drivers \ Segger \ x64

**Comment by cezanne** [comment]
@kmvi-dev : I also installed the microcontroller programming environment. I saw many drivers to be installed. BTW, the device ID's are different between your screenshot(PID:2141) and your USB capture(PID: 2041). Here is a wireshark view loading your capture.

<img width="854" alt="avrmkii" src="https://user-images.githubusercontent.com/242044/80849310-93e94780-8c51-11ea-8224-fdade51f33d4.png">

**Comment by kmvi-dev** [comment]
@cezanne 
different identifiers, because I made a capture from another AVR MKII programming device.
The fundamental difference between a USBIP tunnel and a locally connected  device for programming microchip will be noticeable if you can get a  URB packet from a USBIP hub,
using usbcap. I was unable to get such a log using usbcap, and so I received URB packets from USBIP  using usbsnoop. I can send you its executable module of usbsnoop, which I built and used

**Comment by kmvi-dev** [comment]
@cezanne
or I can, if necessary, send you a screenshots of the capture of URB packets

**Comment by cezanne** [comment]
@kmvi-dev : [A virtual avrispmkii device](https://github.com/cezanne/usbip-vstub) was implemented by usbip-vstub, which was launched to support a virtual stub for usbip-win.
Simple attaching of a virtual avrispmkii did not playback all URB packets of your capture. No more packet was requested after SET_CONFIGURATION. Here's my [kernel log](https://github.com/cezanne/usbip-win/files/4569855/avrmkii.log) and a screenshot.

![avrispmkii](https://user-images.githubusercontent.com/242044/80909789-eddb3180-8d65-11ea-9dac-66ffa0f25082.png)

BTW, HW id's are quite different each other. In my case, HW id has no suffix MI(multiple interface). Could you check? Other capture or screenshot would be helpful.

**Comment by kmvi-dev** [comment]
_>BTW, HW id's are quite different each other. In my case, HW id has no suffix MI(multiple interface). >Could you check? Other capture or screenshot would be helpful_
@cezanne 
ok, during the day I will prepare logs and screenshots of the USPsnoop sniffer in order to more fully determine the problem when forwarding a programming device

**Comment by kmvi-dev** [comment]
@cezanne 
https://drive.google.com/open?id=1v4jPttIJc8Jusdse8wfEPruyvo-pbzU-
you can download the archive file from this link, in which you will find screenshots and logs of URB packet capture when connecting the AVRISP mkII programming device locally-LocalConnect-ok folder, using usbip - UsbIpConnect-Err folder. For comparative analysis, I forwarded the programming device using a commercial VirtualHere tool https://www.virtualhere.com/home. The log and screenshots are in the VirtualhereConnect-ok folder . In the usbsnoop folder are the source and build urb package sniffer modules from the https://github.com/SnoopWare/usbsnoop repository

**Comment by cezanne** [comment]
@kmvi-dev : Thanks for sharing good stuff. I examined all usbsnoop logs. 
As you marked, an usbsnoop log of usbip has quite different URB responses. This may be due to that usbip-win does not deliver down the URB request to the bus.  But Atmel_winusb driver does not care the difference as a avrmkii device are successfully created via usbip-win.
Of course, a device programming application failed to detect my virtual avrmkii device. Even though a physical device object name was forced to "USBPDO-5", it failed to detect.
So, is there any different device property other than physical device object name?

**Comment by kmvi-dev** [comment]
@cezanne 
in the archive https://drive.google.com/open?id=1vxXhnRoYBAXwXNYEYeRYG-_m2fTzaTNc screenshots of the properties of the AVRISP mkII device that are read by usbdview (https://www.nirsoft.net/utils/usb_devices_view.html) during using virtualhere and usbip.

**Comment by cezanne** [comment]
@kmvi-dev : Indeed, your new screenshots nicely show the differences between usbip and virtualhere. I tried to use the same device name but the S/W could not detect.  Other different factors(power or capability) will be tried. An empty power entry of usbip-win seems to be the highest probable cause of this issue but I can't figure out why usbip-win presents no power entry.

**Comment by kmvi-dev** [comment]
I think it still comes from the situation that you commented above
https://github.com/cezanne/usbip-win/issues/111#issuecomment-623406724
>_this may be due to that usbip-win does not deliver down the URB request to the bus_

**Comment by cezanne** [comment]
@kmvi-dev : The vhci driver of usbip-win has not been regarded as a real USB host controller. Because vhci does not support [GUID_DEVINTERFACE_USB_HOST_CONTROLLER](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/guid-devinterface-usb-host-controller). It's a very old weakness.(see #46)  If it is implemented, usbdeview can find the power and usb version of a usbip-win device and empty entries of usbdeview will be resolved.  Of course, device programming S/W is able to find a device virtualized by usbip-win via hub device interface. 

So... I will have a try to implement

**Comment by kmvi-dev** [comment]
@cezanne 
Did I understand you correctly? Will you try to implement this support?
if so, you can contact me if you need to check the driver on problem devices and get logs..

**Comment by cezanne** [comment]
@kmvi-dev :
> Did I understand you correctly? Will you try to implement this support?

Almost correct. I hope that the mentioned  implementation will resolve your issue.

> if so, you can contact me if you need to check the driver on problem devices and get logs..

Sure, I will. Thanks.

**Comment by kmvi-dev** [comment]
@cezanne 
I try according to your prompt https://github.com/cezanne/usbip-win/issues/111#issuecomment-624688638
to develop code for registering the usbip driver as a USB hub, but I can’t.
I have a very vague idea of how to do this.
Could you write me, what needs to be done for such registration of the driver (What kernel functions should be used?).
Or if it’s not difficult for you, indicate where I can read about it.

**Comment by cezanne** [comment]
@kmvi-dev : I'm trying to restructure usbip-win to support a virtual hub enumerated by vhci. I hope that a new branch will be published soon. Anyway, host controller and root hub interface have been already implemented at [roothub branch](https://github.com/cezanne/usbip-win/tree/roothub). But it does not solve your issue because  a location path of a device is not properly configured via GUID_PNP_LOCATION_INTERFACE.

**Comment by kmvi-dev** [comment]
@cezanne this is good news. Thank you. And thank you very much for the roothub branch.
👍

**Comment by cezanne** [comment]
@kmvi-dev : I'm still working but share the [new_vhci branch](https://github.com/cezanne/usbip-win/tree/new_vhci). usbview seems to show usbip-win but other tools(device programming and usbdeview) cannot detect. More IOCTL's should be implemented or revised.

**Comment by cezanne** [comment]
@kmvi-dev : Please check the recent [new_vhci branch](https://github.com/cezanne/usbip-win/tree/new_vhci) and a [release page](https://github.com/cezanne/usbip-win/releases/tag/v0.2.0). Although lots of IOCTL's have been implemented and usbview works well, device programming app does not detect a usbip-win device. usbdeview also fails to show correctly. So, I asked power detection method to the author of usbdeview.

**Comment by kmvi-dev** [comment]
thanks, of course I will definitely check and write about the results

**Comment by kmvi-dev** [comment]
@cezanne 
I can’t install the driver. I install the driver according to README.md in the manual install section, the screenshot is attached
http://prntscr.com/svc6qk
http://prntscr.com/svc740
I get the same thing when calling usbip.exe install

The project was buil in VS-2017
This is the result of the build
http://prntscr.com/svcc1y

This is a list of built binaries 
http://prntscr.com/svcah2

**Comment by cezanne** [comment]
@kmvi-dev : README.md has not been updated. 
You can install manually as follows:
* you should first remove an old usbip_vhci.inf. 
   `CMD> pnputil /enum-drivers`
   You can list up all drivers installed. If you find an old usbip_vhci.inf as oem2.inf, then 
   `CMD> pnputil /delete-driver oem2.inf` 
* install usbip_vhci.inf
  `CMD> pnputil /add-driver usbip_vhci.inf`
* Add legacy hardware. You should select usbip_root.inf

"usbip.exe install" will do upper procecdures. Please confirm that all files are v0.2.0(especially usbip.exe) and usbip_root.inf is copied. My screenshot is attached.

<img width="744" alt="usbip_install" src="https://user-images.githubusercontent.com/242044/83969389-b9c9d200-a90a-11ea-95c7-4ab3df560f33.png">

**Comment by kmvi-dev** [comment]
@cezanne 
Thank you .
Ok,I will do according to your recommendation

**Comment by kmvi-dev** [comment]
@cezanne 
I have done according to your recommendations

http://prntscr.com/svdqfj - ok
http://prntscr.com/svdr2n
http://prntscr.com/svdrod

**Comment by cezanne** [comment]
@kmvi-dev : Please check a [new vhci](https://github.com/cezanne/usbip-win/releases/tag/v0.3.0),  which is based on KMDF UDE not WDM. A  new UDE-based vhci driver is able to work with usbdeview.

**Comment by kmvi-dev** [comment]
@cezanne 
I checked the version of KMDF UDE on my microcontroller programming device in IDE avr and confirm that this driver version is working with the programming device that is built on the microcontroller from Microchip Technology Inc.
 Thank you very much.
