### ISSUE TITLE
Windows server - Windows client

### ISSUE THREAD

**Issue by bartek012** [cezanne/usbip-win#123]
Hello,
Is it even possible to use usbip in this configuration (Windows10 server - Windows10 client)? 

I have problem with installing vhci driver. I've tried to install it manually by Add Hardware option (usbip_vhci.inf). It says "The folder you specified doesn't contain a compatible software driver for your device. If the folder contains a driver, make sure it is designed to work with Windows for x64-based system". Am I choosing wrong file? 

I have used usbip-win 0.0.8 release and ran 
**server side**
usbip bind -b 1-2
usbipd -4- d 

**client side**
I can see binded device using "list -r <ip>" command
but when I try to attach it, there is an error : open vhci driver, failed to read err: 0x6

output from server console : 

usbipd: info: starting usbipd (usbip 1.0.0)
usbip: debug: C:\work\usbip-win\userspace\src\usbipd\usbipd_sock.c:38:[build_sockfd] opening 0.0.0.0:3240
usbip: info: listening on 0.0.0.0:3240
usbip: info: connection from 10.8.14.18:49959
usbip: info: recv_pdu: received request: 0x8003 - attach device
usbip: debug: C:\work\usbip-win\userspace\src\usbipd\usbipd_import.c:18:[forwarder_stub] stub forwarding started
usbip: debug: C:\work\usbip-win\userspace\src\usbipd\usbipd_import.c:108:[recv_request_import] import request busid 1-2: complete
usbip: info: recv_pdu: request 0x8003: complete
usbip: debug: C:\work\usbip-win\userspace\src\usbipd\usbipd_import.c:28:[forwarder_stub] stub forwarding stopped

Thanks

**Comment by Jesuslcp** [comment]
Yes, no problem to run W10 x64 and W10x64, I did with this version, please be sure you launch both sides with administrator privileges.

**Comment by bartek012** [comment]
Yes, but what if none of the following doesn't work? You could install VHCI driver without any problem?

![image](https://user-images.githubusercontent.com/62341455/77056904-6d3dbd00-69d3-11ea-9bda-07bfa719d3a7.png)


![image](https://user-images.githubusercontent.com/62341455/77057186-e0dfca00-69d3-11ea-81bd-9f96044125c5.png)

After choosing path C:\USBIP\driver\vhci

![image](https://user-images.githubusercontent.com/62341455/77057314-0d93e180-69d4-11ea-8644-492eb38440b9.png)

**Comment by bartek012** [comment]
@Jesuslcp  which option worked in your case command line install or manual ? 

Is there any other option to install vhci driver?

**Comment by Jesuslcp** [comment]
I installed both manually in W10 and W7, with no issues, except for W7 that I had to compile for this OS as the W10 driver compiled wasn't working properly.

I have to say that previous to compile, I ran an VS self analysis and depuration of the source code, detecting some issues  changed.

If you need it, I can provide my SC and compiled files to check.

**Comment by bartek012** [comment]
@Jesuslcp I would be grateful for that files, Thanks. 
My email: bartk970802@gmail.com

**Comment by Jesuslcp** [comment]
Here they are!!

[USBIP Source Code 0.0.8 MOD Jesuslcp.zip](https://github.com/cezanne/usbip-win/files/4359914/USBIP.Source.Code.0.0.8.MOD.Jesuslcp.zip)
[USBIP 0.0.8 MOD Jesuslcp Windows x64.zip](https://github.com/cezanne/usbip-win/files/4359915/USBIP.0.0.8.MOD.Jesuslcp.Windows.x64.zip)

**Comment by bartek012** [comment]
Thank you ;)

**Comment by Jesuslcp** [comment]
You are very welcome! Let us know if this compiled works also for you!

**Comment by bartek012** [comment]
It works !!
your version of usbip_vhci.inf file passed through manual install.
Problem solved thank you again. 

Differences between files  (left side is working)
![image](https://user-images.githubusercontent.com/62341455/77171888-62f7ed80-6abd-11ea-90ff-cd94b147015a.png)

**Comment by Jesuslcp** [comment]
Great! Will have a look to that when I found the moment.

**Comment by Jesuslcp** [comment]
Well, after have a look to the problem with the driver, there's no problem. Simply you have taken the driver directly from the source code, but usbip_vhci.inf is modified to the correct architecture during the built process.

**Comment by cezanne** [comment]
@bartek012 @Jesuslcp : This issue seems to be resolved. 😃 I'm going to close.
