### ISSUE TITLE
Possible invalid driver installed after BSOD

### ISSUE THREAD

**Issue by bartlomiejcieszkowski** [cezanne/usbip-win#132]
Thats actually windows fault :)

When bsod happens windows can store a copy of .sys and show yellow banged usbip vhci driver, when we will install driver with a
`usbip.exe install`

old driver can be installed

Manual check is to check if the driver in %WINDOWS%\System32\ is the same as the one we have in a folder.

TODO - We should explore if we can check that the driver installed by os is the same as we wanted, it should be possible.

**Comment by cezanne** [comment]
@bartlomiejcieszkowski : I'll close it. Please reopen if you need.
