### ISSUE TITLE
mismatch version between linux and usbip.exe [usbip (usbip 1.0.0)]

### ISSUE THREAD

**Issue by nakhla** [cezanne/usbip-win#140]
hello
Thank you for this great piece  of software, I am happy that there are some attempts to port usbip to windows, I am interested to make a windows as a server and use ordinary usbip client on Ubuntu bionic minimal version,

I downloaded usbip 0.9 release and signed the certificate in both mentioned locations.
I am able to list devices running this command `usbip.exe list -l` and `binding usbip.exe bind -b 1-96`
and run the daemon for listening `usbipd.exe -d -4`
but when i try to attach the usb device from client in my ubuntu using this command
```
$ usbip attach -r 192.168.1.30 -b 1-59
usbip: error: recv op_common
usbip: error: query
```
I got the above error
and after some investigations I found that this error due to a usbip-utils version mismatch between the client and server. 
After executing `usbip version` in the Client  Ubuntu bionic I got `usbip (usbip-utils 2.0)`
but in `usbip.exe` in windows  server I got`[ usbip (usbip 1.0.0)]`

![2020-04-16_202343ff](https://user-images.githubusercontent.com/16466660/79494957-2966c380-8024-11ea-8768-12655caaf516.jpg)

Is that right or I am missing something? and what is the solution?

**Comment by cezanne** [comment]
@nakhla : try to attach 1-96 not 1-59.

**Comment by cezanne** [comment]
@nakhla : Close the old issue. Please reopen if you need.
