### ISSUE TITLE
attach failure with device status code 28

### ISSUE THREAD

**Issue by muhammadhaqyaunoora** [cezanne/usbip-win#142]
So, I am currently trying to connect to my Arduino Uno remotely using USBIP via Raspberry Pi 3 B. The problem that I currently have is that all of the information about the Arduino (which can be seen on the Raspberry) cannot be seen on the Windows 10 client. Besides that, whenever I tried to 
bind to the Arduino my Windows 10 client cannot find the correct driver and only shows USB Device over IP (I will attach some screenshots below). I am pretty sure I have followed the steps correctly and already tried solutions from older issues but nothing seems to worked out yet.
![Raspi](https://user-images.githubusercontent.com/47627425/79705306-6dd1b800-82df-11ea-8636-2788336863f2.png)
![Client](https://user-images.githubusercontent.com/47627425/79705403-cb660480-82df-11ea-9a44-784634b272e1.png)
![Device](https://user-images.githubusercontent.com/47627425/79705437-ea649680-82df-11ea-947a-cfc9d8962587.png)

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : Which version did you test ? `root\usbipenum` in your screenshot is a very old vhci device name. A recent one is `root\usbip_vhci`. Check your `usbip_vhci.inf`.

**Comment by muhammadhaqyaunoora** [comment]
@cezanne I think I forgot to delete the old version of the vhci. I just tried redoing everything again with the most recent one from this repository and it still does the same as before.
Here is the screenshot from the usbip_vhci.inf.
![usbip_vhci inf1](https://user-images.githubusercontent.com/47627425/80668208-6f636300-8acb-11ea-9cb5-9b7a4f5a9f44.png)
![usbip_vhci inf2](https://user-images.githubusercontent.com/47627425/80668250-902bb880-8acb-11ea-9245-6fbc37da023b.png)
And here is what I got after redoing everything
![image](https://user-images.githubusercontent.com/47627425/80668319-c36e4780-8acb-11ea-8201-2f17bebb2d41.png)
![image](https://user-images.githubusercontent.com/47627425/80668345-da149e80-8acb-11ea-8c35-3eca1a1a0d75.png)

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : What is the device which you want to attach? Code 28 may indicate that there's no function driver. Did you install a driver for a device to be attached?

**Comment by muhammadhaqyaunoora** [comment]
I tried to attach to Arduino Uno and the driver is already installed

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : 
> I am trying to attach to Arduino Uno and the driver is already installed

I see. Can you share kernel log or USB capture. Please refer https://github.com/cezanne/usbip-win/issues/144#issuecomment-619335255 .

**Comment by muhammadhaqyaunoora** [comment]
This is the USB Capture
https://www.upload.ee/files/11602733/arduinocapt.pcap.html

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : Thanks for the capture. Is it obtained while the arduino is directly attached without usbip-win? It seems too short. See my wireshark screenshot for your capture.

![arduino](https://user-images.githubusercontent.com/242044/80786972-293bfb80-8bc0-11ea-8711-fa6ff267797b.png)

**Comment by muhammadhaqyaunoora** [comment]
yes, it was attached directly to my laptop, do I need to attach it via the usbip-win?

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : 
> do I need to attach it via the usbip-win?

No. A log with no usbip-win is required.
Then your usb capture is too simple. What is your device number among 1.5.0, 1.4.0, 1.3.0 in screenshot ?

**Comment by muhammadhaqyaunoora** [comment]
I think it was the 1.4.0, or is it better if I did another capture?

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : Yes please..

**Comment by muhammadhaqyaunoora** [comment]
https://www.upload.ee/files/11603318/arduinocapt2.pcap.html
In this one I capture it from when I plugged the cable in until I plugged it off again. Sorry for the bother.

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : This capture seems good..

**Comment by muhammadhaqyaunoora** [comment]
Are there anything else that I could try to help resolve this problem?

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : Where's arduino driver SW? Just install arduino IDE?

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : I have checked that arduino uno works correctly. Please retry with v0.1.0, an up-to-date release.

**Comment by muhammadhaqyaunoora** [comment]
> @muhammadhaqyaunoora : I have checked that arduino uno works correctly. Please retry with v0.1.0, an up-to-date release.

Can you give a screenshot of how it look like on your device? Because it is still showing code 28 on mine, and when I checked the usbip list it is still not showing the device information after I retried using the v0.1.0.
![Client3](https://user-images.githubusercontent.com/47627425/80854873-bdac6980-8c65-11ea-90be-534dd699e93f.png)
![image](https://user-images.githubusercontent.com/47627425/80854883-d1f06680-8c65-11ea-8b5b-e1ba68b72150.png)

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : 
A device is successfully attached with vstub.
<img width="661" alt="arduino" src="https://user-images.githubusercontent.com/242044/80857904-974ff380-8c90-11ea-9005-91221c04a1ef.png">

This is a [vhci kernel log](https://github.com/cezanne/usbip-win/files/4567251/arduino.log).
Well, I have checked that all URB's were invoked as your USB captured log. But `STATUS_NOT_SUPPORTED` in last part of my log should be more investigated.

Anyway, one suspicious thing in your screenshot, why did you stop attach command with ctrl+c ? Usually, `usbip detach -p 1` would be the best way for detaching the device.

**Comment by muhammadhaqyaunoora** [comment]
Do you think another log while using usbip could help investigate the problem? Because I haven't done that yet. And for that ctrl+c situation, that is just me panicking because my laptop started to slow down and I'm afraid if I open another window it would hang. I guess I opened too many applications when I did the trial, nothing to worry about that.

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : 
> Do you think another capture while using usbip could help investigate the problem? 

No.. Instead, can you share your kernel log? Kernel log generation method is described in README.md.

**Comment by muhammadhaqyaunoora** [comment]
Here it is. I did attach and detach while logging. I hope this is good enough.
[haqysarduino.LOG](https://github.com/cezanne/usbip-win/files/4569625/haqysarduino.LOG)

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : Please check again that you *did install* an arduino driver on an attaching machine. I had the same log with yours when there was no arduino driver installed.

**Comment by muhammadhaqyaunoora** [comment]
Okay, it seems to clears up the problem a little bit but I got a new problem with it which is a code 10. I have installed the latest driver by the way.
![image](https://user-images.githubusercontent.com/47627425/80937637-29c2d500-8e00-11ea-843b-6f597c0f2f6d.png)

**Comment by muhammadhaqyaunoora** [comment]
Okay, I installed the latest driver and my laptop now recognizes the Arduino but it throws code 10 and I have tried many solutions from the internet but none works yet.
![image](https://user-images.githubusercontent.com/47627425/80938406-385ebb80-8e03-11ea-9920-1150fd9ae630.png)

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : How about kernel logs in that case?

**Comment by muhammadhaqyaunoora** [comment]
Here it is, I saw slight differences with your log but I cannot really tell what seems to be the problem.
[haqysarduino2.LOG](https://github.com/cezanne/usbip-win/files/4572988/haqysarduino2.LOG)

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : In your log, there's a warning to cause your device to work incorrectly.
```
00000206	0.03614570	usbip_vhci:(WW) URB_FUNCTION_SELECT_INTERFACE: wrong status: USBD_STATUS_STALL_PID
```
I have no idea about why stall occurred. Please check your usbip_vhci.sys is up-to-date.

**Comment by muhammadhaqyaunoora** [comment]
I redownloaded that file from the v0.1.0 release, but it was still showing code 10 and that stall warning.

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : Ok, I'll try to  get a physical arduino and test.

**Comment by muhammadhaqyaunoora** [comment]
Do you think it is something to do with my laptop? Or are there other things that might cause this problem?

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : 
> Do you think it is something to do with my laptop? Or are there other things that might cause this problem?

I'm not sure but your laptop has no problem if arduino works well without usbip-win. I'm still trying to find a physical arduino. 😞

**Comment by muhammadhaqyaunoora** [comment]
Ooh, okay. I will try looking for a way to troubleshoot while waiting updates from you. Thanks for your help, I really appreciate it.

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : How about trying with the latest usbip-win version ?

**Comment by cezanne** [comment]
@muhammadhaqyaunoora : I'll close it. Please reopen if you need.
