### ISSUE TITLE
Silicon Labs CP210x - Error

### ISSUE THREAD

**Issue by pasha-zzz** [cezanne/usbip-win#144]
Server: ARM Linux 4.4.219 (DD-WRT)
Client: Windows 10 x64 1909

After attach I can see device (child of USB/IP VHCI) but with exclamation mark. Info is "This device cannot start. (Code 10)
An invalid parameter was passed to a service or function."

When attach device to Windows machine directly - it works fine.
USB\VID_10C4&PID_EA60&REV_0100

**Comment by cezanne** [comment]
@pasha-zzz : Windows kernel log is required to resolve your issue. Log generation methods are described in README.md. Or USB packet logs of directly attached your device would be helpful. One of such a tool is [USBPcap](https://desowin.org/usbpcap/).

**Comment by pasha-zzz** [comment]
USBPCap file:
https://www.upload.ee/files/11559558/CP210x.pcap.html
https://sendit.cloud/4g2pwg22r9fm

**Comment by cezanne** [comment]
@pasha-zzz : Thanks for the USBPCap file. I'm trying to make a virtual CP210x device via [usbip-vstub](https://github.com/cezanne/usbip-vstub). Maybe the device needs a function driver. Can you share a CP210x driver ?

**Comment by pasha-zzz** [comment]
https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers

**Comment by cezanne** [comment]
A vstub for cp210x is implemented and here is client-side(vhci) [kernel log].(https://github.com/cezanne/usbip-win/files/4538360/DESKTOP-3V3FHQU.LOG)

I had tested it with [control_transfer branch](https://github.com/cezanne/usbip-win/tree/control_transfer). As shown in the log file, the device was removed after a fifth URB_FUNCTION_CONTROL_TRANSFER(seq num: 16) was executed.

@pasha-zzz : Could you share a kernel log with a real cp210x device?

**Comment by cezanne** [comment]
@pasha-zzz : Here is a builtin binary [vhci driver](https://github.com/cezanne/usbip-win/files/4538727/usbip_vhci.zip).

**Comment by pasha-zzz** [comment]
> Could you share a kernel log with a real cp210x device?

Instructions for kernel logging are not full.

- Add registry key and reboot
- DebugView is a good tool to view
- Thats all

But I not need view. I want collect logs. And what I must do with device? Eject, plug, or maybe real data exchange through virtula COM is needed?

**Comment by cezanne** [comment]
@pasha-zzz : Did you install DebugView successfully ? Some options of debugview should be marked like as a below figure.
<img width="347" alt="debugview" src="https://user-images.githubusercontent.com/242044/80571729-0e3e7f80-8a38-11ea-97ba-b6bf2f935032.png">

> But I not need view. I want collect logs. And what I must do with device? Eject, plug, or maybe real data exchange through virtula COM is needed?

I need kernel logs of usbip-win with a real cp210x. For now, when getting logs, ejection or any other action is not required.

**Comment by pasha-zzz** [comment]
Kernel logs of attach command. Scenario like in 1st message:
https://www.upload.ee/files/11594031/usbip-win.zip.html
https://sendit.cloud/oubcdsdm77xq

**Comment by cezanne** [comment]
@pasha-zzz : You don't need to attach a file using an external service. Github supports file attachmenent in comment dialog. 
Anyway,  a kernel log of your https://sendit.cloud/oubcdsdm77xq does not seem to be obtained from an up-to-date vhci driver. Because a following log cannot be generated.
```
00000475	1.77483726	usbip_vhci:(WW) process_irp_urb_req: unhandled function: URB_FUNCTION_CONTROL_TRANSFER: len: 136
```

[This](https://github.com/cezanne/usbip-win/files/4556991/cp210.LOG)  is my kernel log via usbip-vstub. The recent vhci driver seems to be able to handle a cp210x properly.

**Comment by pasha-zzz** [comment]
Sorry, I didnt think that only driver is sufficient for correction! Reistalled driver and all work fine. Thanks a lot!

**Comment by cezanne** [comment]
@pasha-zzz : Good to hear.. Please close this issue later if your issue will be resolved.
