### ISSUE TITLE
USBIP bind error 

### ISSUE THREAD

**Issue by LEYXIAO** [cezanne/usbip-win#156]
hi.

when I bind the BUSID,something error,for windows 10 usbip server.

like this:

F:\new\usbip-win-master\Debug\x64>usbip.exe bind -b 1-87
usbip: error: failed to update driver: e0000242
usbip: error: bind_device: error binding device on busid 1-87: err: 0

how can I solve it?

thinks!

**Comment by koudis** [comment]
The usbip server part is not tested well. I suppose to use Linux a server.

**Comment by cezanne** [comment]
@LEYXIAO : Please refer https://github.com/cezanne/usbip-win/issues/32#issuecomment-489973320
I'll close this issue. Please reopen if you wish.
