### ISSUE TITLE
[BUG] Stops working after upgrading to ubuntu kernel 5.4.0-31

### ISSUE THREAD

**Issue by simon-on-gh** [cezanne/usbip-win#161]
usbip was working great with my office all-in-one printer&scanner on the ubuntu (kernel 5.3.0-51) server before, but the scanner part stops working after upgrading the kernel 5.4.0-31. 

The printer is still functioning, though 

Client shows 
```
           : /sys/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.2
           : (Defined at Interface level) (00/00/00)
           :  0 - Printer / Printer / Bidirectional (07/01/02)
           :  1 - Vendor Specific Class / Vendor Specific Subclass / Vendor Specific Protocol (ff/ff/ff)
           :  2 - Vendor Specific Class / Vendor Specific Subclass / Vendor Specific Protocol (ff/ff/ff)
```

Both client and server shows no error message.

**Comment by wrenchonline** [comment]
I have extracted Linux usbip kernel code to compile and run.Sometimes you have to make sure that the kernel version runs.

**Comment by simon-on-gh** [comment]
Works again after unplug and rebooting, close for now
