### ISSUE TITLE
Distribute Release as a single zip PLEASE

### ISSUE THREAD

**Issue by Merith-TK** [cezanne/usbip-win#166]
As the title says, could you PLEASE distribute related files together? so i dont have to download every single file individually, find them in my downloads folder, and move them to the new location?

**Comment by Merith-TK** [comment]
[usbip_win.zip](https://github.com/cezanne/usbip-win/files/4741203/usbip_win.zip)
I packaged this by just downloading and zipping

**Comment by koudis** [comment]
Look at
https://github.com/cezanne/usbip-win/issues/162

You must uninstall previous usbip_vhci driver and the Windows test mode must be enabled.

**Comment by septatrix** [comment]
Why are these files distributed separate anyway? It feels like they could simply be included in the exe (which could unpack them if necessary)

**Comment by Merith-TK** [comment]
They are inherently seperate because of how windows loads crap. also easier to distribute.
However. having seperate files is DIFFERENT, than having a release, for every single file

**Comment by cezanne** [comment]
@Merith-TK : I agree that a single zip would be better. I'll try.

**Comment by Merith-TK** [comment]
If you compile to a folder, you can simply zip that folder and release it.
