### ISSUE TITLE
Does usbip-win support winusb and webusb?

### ISSUE THREAD

**Issue by versaloon** [cezanne/usbip-win#169]
I tested usbip with a winusb+webusb device, but failed. And I recoreded all the transactions on the server side(server side is a PC software enumlating a USB device, client side is usbip-win):
![usbip_dfu_list](https://user-images.githubusercontent.com/3937783/85221673-5189ee80-b3e8-11ea-8ce0-0156a3afee3e.png)
![usbip_dfu_import](https://user-images.githubusercontent.com/3937783/85221674-52bb1b80-b3e8-11ea-9925-d2b4af795310.png)

In the image, usbip_server: send indicates the data sent to the usbip-win32.
While usbip_server: recv indicates the data received from the usbip-win32.

I found that after IMPORT, the first URB is quite strange, normally, it should be a ReadDeviceDescriptor, but in the image, it's ReadConfigurationDescriptor.

**Comment by cezanne** [comment]
@versaloon : Which version did you test ?

**Comment by versaloon** [comment]
> @versaloon : Which version did you test ?

0.2.0, I will later test the latest version

**Comment by windowsair** [comment]
It seems that the order of requests has always been the same. In addition, the winusb request will not be initiated...

**Comment by cezanne** [comment]
@versaloon : Could you describe a your problem in more detail? I have confirmed that an attached device is queried by a simple WinUSB application using both vhci versions(ude or wdm).

**Comment by versaloon** [comment]
@cezanne OK, I will try the latest version.
