### ISSUE TITLE
No support usb composite device on usbip 0.2.0

### ISSUE THREAD

**Issue by 519790441** [cezanne/usbip-win#175]
I have a usb composite device. When mapping via usbip, the device ID seen from "usbip attach" and the device ID seen after "attach" are not equal.
Through the "dbgview" window, you can see that after the bulk request reaches the "stub" endpoint, it will deadlock until the peer manually performs the "detach" operation.
![image](https://user-images.githubusercontent.com/58975525/86082040-74dc2a00-bac9-11ea-8334-d4e1fdf68825.png)
![image](https://user-images.githubusercontent.com/58975525/86082208-c684b480-bac9-11ea-95da-9bec7e6db643.png)

When mapping through the "usb over remote desktop" software, the local device ID and the remote device ID are equal, and the device can work normally on the remote computer.

**Comment by cezanne** [comment]
@519790441 : Please check a new v0.3.0 in the [release page](https://github.com/cezanne/usbip-win/releases/). And I have marked v0.2.0 as obsolete.

**Comment by 519790441** [comment]
> obsolete

The v0.3.0 still fails.
I can get "usbip_stub: get_desc: Unknown descriptor type code: 22" in dbgview before deadlock.
![image](https://user-images.githubusercontent.com/58975525/86196317-939ff680-bb85-11ea-91c2-e10a1c40675c.png)

**Comment by 519790441** [comment]
In 0.3.0, I can get bsod when detach from stub manually.
0: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

DRIVER_IRQL_NOT_LESS_OR_EQUAL (d1)
An attempt was made to access a pageable (or completely invalid) address at an
interrupt request level (IRQL) that is too high.  This is usually
caused by drivers using improper addresses.
If kernel debugger is available get stack backtrace.
Arguments:
Arg1: fffff80728c24b60, memory referenced
Arg2: 0000000000000002, IRQL
Arg3: 0000000000000008, value 0 = read operation, 1 = write operation
Arg4: fffff80728c24b60, address which referenced memory

**Comment by 519790441** [comment]
![image](https://user-images.githubusercontent.com/58975525/86783620-24e60000-c093-11ea-8991-e8d54d800d93.png)
I can get "usbip_vhci:(WW) process_irp_urb_req: unhandled function: URB_FUNCTION_GET_MS_FEATURE_DESCRIPTOR: len: 136" on vhci endpoint. @cezanne

**Comment by 519790441** [comment]
I used the new vhci_ude mode and currently solve the problem I mentioned in the post. @cezanne

**Comment by cezanne** [comment]
@519790441 : Thanks for your report. I'll close this issue. Please reopen if you need.
