### ISSUE TITLE
 usbip-win-0.3.0 ，Is the USBIP version 1.0.0?

### ISSUE THREAD

**Issue by hnwentao** [cezanne/usbip-win#181]
![Snipaste_2020-07-12_16-43-48](https://user-images.githubusercontent.com/68153000/87242415-0b600200-c45f-11ea-8fd9-84791be3b60f.png)
![2](https://user-images.githubusercontent.com/68153000/87242418-0dc25c00-c45f-11ea-953e-ee2a9fadf266.png)
![222](https://user-images.githubusercontent.com/68153000/87242541-3139d680-c460-11ea-8a5c-4acf5ea62368.png)
ubuntu20.04 linux server, window7 x64 client; usbip server version is 2.0, how to switch usbip-win-0.3.0 to version 2.0；but Windows10 Professional Edition, you can attach to USB device。
![333](https://user-images.githubusercontent.com/68153000/87243636-21bf8b00-c46a-11ea-948b-756a20ed29b8.png)

**Comment by Wqrld** [comment]
0.3.0 is usbip 1.0 yes

**Comment by cezanne** [comment]
@hnwentao : A version string of usbip.exe or usbipd.exe does not match with a release version. I'll fix that. 
I think that all usbip-win releases are compatible with usbip-utils 2.0.
