### ISSUE TITLE
unable to connect to 192.168.180.22 port 3240

### ISSUE THREAD

**Issue by k-str50** [cezanne/usbip-win#184]
Hi,
I'm not sure what's wrong.
I try to use usbip win 0.3.0.
Making and installing the usbip v0.3.0 is fine.
```
PS C:\Users\Kurt\usbipV0.3.0> .\usbip.exe install_ude
usbip: info: vhci(ude) driver installed successfully
```
Even in the device manager there is a new device called **_usbip-win VHCI(ude)_**
But.. when I execute the command to attach the remote device:
```
PS C:\Users\Kurt\usbipV0.3.0> .\usbip.exe attach_ude -r 192.168.180.22 -b 1-1
usbip: error: recv op_common
usbip: error: read_devbuf: failed to read: err: 0x6
```
On the raspberry I find this:
```
pi@raspberrypi:~ $ usbip list -l
 - busid 1-1 (05e3:0702)
   Genesys Logic, Inc. : USB 2.0 IDE Adapter [GL811E] (05e3:0702)
```
The version of usbip is
```
**On raspberry:**
pi@raspberrypi:~ $ **_usbip version_**
usbip (usbip-utils 2.0)
and 
**on windows client:**
PS C:\Users\Kurt\usbipV0.3.0> **_.\usbip.exe version_**
usbip (usbip 1.0.0)
```
I have no idea whats wrong.
Please help!
Thanks a lot in advance!

**Comment by Chris2011** [comment]
If you got it working, it would be good for everyone to know your solution :). It worked for couple of hours ago after whatever reason, I got the exact same result: usbip: error: unable to connect to 192.168.178.42 port 3240:

So please tell us, how did you solve it? Raspi as my USB Server is working just fine, I'm using Windows and just `usbip.exe list -r <ip>` is not working and shows me this error.

**Comment by Chris2011** [comment]
If you got it working, it would be good for everyone to know your solution :). It worked for couple of hours ago after whatever reason, I got the exact same result: usbip: error: unable to connect to 192.168.111.11 port 3240:

So please tell us, how did you solve it? Raspi as my USB Server is working just fine, I'm using Windows and just usbip.exe list -r <ip> is not working and shows me this error.

**Comment by Chris2011** [comment]
Ok for me and for everyone else, the usbipd daemon wasn't running anymore. Not it is working again. Just use `usbipd -D`
