### ISSUE TITLE
0.3.0-ude usbip_vhci_attach_device: DeviceIoControl failed: err: 0x57

### ISSUE THREAD

**Issue by versaloon** [cezanne/usbip-win#189]
I tested the latest 0.3.0 ude release, with errors below:
![usbip_0 3 0](https://user-images.githubusercontent.com/3937783/87625429-b5d86d80-c75c-11ea-88a4-19dfb0c8fa31.png)

**Comment by cezanne** [comment]
@versaloon : Did you want to test a ude version ? If so, you should use \'attach_ude\' instead of \'attach\' comand.

**Comment by cezanne** [comment]
@versaloon : I'll close this issue.
