### ISSUE TITLE
Cannt compile Release builds of vhci_ude branch

### ISSUE THREAD

**Issue by pasha-zzz** [cezanne/usbip-win#190]
1st error is:

`C:\projects\usbip-win-new\Release\x64\usbip_vhci_ude\vhci_ioctl.tmh(1319,71): error C4013: 'dbg_vhci_ioctl_code' undefined; assuming extern returning int [C:\projects\usbip-win-new\driver\vhci_ude\usbip_vhci_ude.vcxproj]`

**Comment by cezanne** [comment]
@pasha-zzz : The error is due to that WPP messages are using debug routines such as `dbg_vhci_ioctl_code()`.  
BTW, the vhci_ude branch has some problems. So it's not ready to resolve this issue right now. 
Please use a debug mode or create a PR for release build. :smiley:
