### ISSUE TITLE
Missing Serial Number and Device Name 

### ISSUE THREAD

**Issue by jakjablonski** [cezanne/usbip-win#192]
Hi,

I'm trying to share usb devices using your software and I found 2 issues.

1. Missing Device Name and Serial Number
Server:
![image](https://user-images.githubusercontent.com/18118792/89415662-7635ed80-d72c-11ea-8eb4-235a841e7dbb.png)
Client:
![image](https://user-images.githubusercontent.com/18118792/89415599-5d2d3c80-d72c-11ea-91fd-e97f267ffbdc.png)

Device Name has changed to HPDO and Serial Number is missing

2. Max length of the serial number is too small
After setting this line to 18 - #define MAX_VHCI_INSTANCE_ID  16 -> 18
Then I can assign a longer serial number when attaching USB on Windows.
usbip.exe attach -r 192.168.0.1 -b 5-1.1 -i  4600000D0D221600

**Comment by olehkon** [comment]
![image](https://user-images.githubusercontent.com/37936904/89447527-616e4f80-d756-11ea-95f2-ce84148cf6f7.png)
The serial number is present in the log when connected to the client.

**Comment by cezanne** [comment]
@jakjablonski : 
1. Missing Device Name and Serial Number
    I gave up USBdeview working for vhci(WDM). It was too complicated to emulate a virtual hub. That's why I was starting to develop vhci(ude). See #111
2. Max length of the serial number is too small
   I got it. Sadly, vhci(ude) does not support a customized instance id. It can be TODO.

**Comment by cezanne** [comment]
@jakjablonski @olehkon : Please check [this wiki](https://github.com/cezanne/usbip-win/wiki/Deployment-Tips#usb-serial-overwriting)

**Comment by cezanne** [comment]
@jakjablonski : I'm going to close this isuse. Please reopen if you want.
