### ISSUE TITLE
Will the drivers eventually get a signed certificate?

### ISSUE THREAD

**Issue by KieranDevvs** [cezanne/usbip-win#198]
Will the drivers eventually get a signed certificate, so that we don't have to disable certificate signature enforcement every time we use USB/IP?

**Comment by jenglilu** [comment]
usbip_win project target on Win10(x64) OS, build usbip driver(with EV Code Signing). Install usbip driver on trusted platform module. The driver cannot be installed due to an exception(error:52).
Does the driver fail to install must go through WHQL inspection and review?
