### ISSUE TITLE
Pendig irp read cancelled

### ISSUE THREAD

**Issue by channabasappakolachi** [cezanne/usbip-win#200]
USP-IP Server                          : on Raspberry Pi zero-w
USB-IP Client                           : usbip-win-0.1.0  on Windows 10  
Device connected on server    : mouse
```
command :  usbip.exe list -r 192.168.4.1
Response : 
Exportable USB devices
======================
 - 192.168.4.1
        1-1: Pixart Imaging, Inc. : Optical Mouse (093a:2510)
           : /sys/devices/platform/soc/20980000.usb/usb1/1-1
           : (Defined at Interface level) (00/00/00)
           :  0 - Human Interface Device / Boot Interface Subclass / Mouse (03/01/02)
```

Command :                            usbip.exe attach -r 192.168.4.1 -b 1-1
Response :                             No response . Simply going out of the command .
Observation on server :         server getting disconnect command from client !!!!!
Observation debug log  : 
```
                                             usbip_vhci: pending irp read cancelled FFFF950762E08D50	
	                                     usbip_vhci: vhci_ioctl: Enter FFFF95077351E090	
	                                     usbip_vhci: ioctl code: IOCTL_USBIP_VHCI_UNPLUG_HARDWARE	
	                                     usbip_vhci: Plugging out single device: port: 1	
	                                     usbip_vhci: found device: port: 1	
                                             usbip_vhci: Plugging out: port: 1	
	                                     usbip_vhci: finish pending irp	
	                                     usbip_vhci: Device 1 plug out finished
```
Detailed log file is attached below : 

[RasPi_Mouse_Error.LOG](https://github.com/cezanne/usbip-win/files/5409351/RasPi_Mouse_Error.LOG)
![Screenshot 2020-10-20 200512](https://user-images.githubusercontent.com/12229756/96601416-9f1f5500-130f-11eb-9454-45ff8051ba1d.jpg)

**Comment by cezanne** [comment]
@channabasappakolachi :
> Command : usbip.exe attach -r 192.168.4.1 -b 1-1
Response : No response . Simply going out of the command .

Your attach command worked correctly. See https://github.com/cezanne/usbip-win/issues/34#issuecomment-489979068.
The command did not respond, so maybe you pressed Ctrl+C.
There are no errors in the vhci debug log and the output message 'pending irp read cancelled' usually appears when a virtual device is plugged out.
