### ISSUE TITLE
In ude mode, Bulk transfer seem to be slower than Interrupt transfer?

### ISSUE THREAD

**Issue by windowsair** [cezanne/usbip-win#208]
Thank you for your excellent work in ude mode!

The following are the average time results of transmission under winusb (Bulk) and HID (interrupt). 

> Take the result of the first transmission here, and transmit the same 2 bytes of data.(In fact, the length of HID transmission is longer, but it takes less time)

1.  Bulk

![image](https://user-images.githubusercontent.com/17078589/98822243-8ec04d00-246b-11eb-8d02-b8bf7157e2ca.png)

2.  Interrupt

![image](https://user-images.githubusercontent.com/17078589/98823544-368a4a80-246d-11eb-8470-58d4f8812dd1.png)

I am not sure what caused the performance loss of bulk transmission.  Do you have any ideas, thanks!:heart:

**Comment by cezanne** [comment]
@windowsair : There's no big difference at vhci code level. Did bulk and interrupt use the same device? If not, HW factor might be important. If so, we can suspect driver stacks for each case.

**Comment by windowsair** [comment]
Hi, @cezanne

Yes, I use the same hardware for transmission. I'm not sure what caused it

**Comment by cezanne** [comment]
@windowsair : bulk case seems to work with more driver stacks including a winusb layer. That would be the reason why bulk is slower.

**Comment by windowsair** [comment]
@cezanne Umm, this is probably an important reason. 

Is this related to HID? It seems that under HID, the host is more actively requesting data from the device endpoint
