### ISSUE TITLE
Share By SessionId

### ISSUE THREAD

**Issue by Saeed-Rezaee** [cezanne/usbip-win#210]
how can we share a usb device that just the very same user who has shared the usb can use , read and write to device and not other users in other sessions in windows?

**Comment by cezanne** [comment]
@Saeed-Rezaee : Do you mean authentication for usbip? If so, it's a very tough issue. usbip protocol does not support that.

**Comment by cezanne** [comment]
@Saeed-Rezaee : This issue will be closed. Please reopen if you need.
