### ISSUE TITLE
Add a timeout or keepalive in case of unexpected disconnection of the client

### ISSUE THREAD

**Issue by csphoenix1** [cezanne/usbip-win#211]
Hi :)

When my USBIP client (eg. Windows) crash, or endured an unfortunate disconnection, the device binded on the remote USBIP server is still attached.
So when my client has just restarted, it can't attach the device, because the device is already attached.

Is there a possibility to add a feature to avoid it?
Eg. add the timeout or a keepalive between client and host. In that case, if the client not answer the server, the server will detach the device.
Eg. or, let the client the availability to force a detach/attach with the server ?

Thank you :)

**Comment by cezanne** [comment]
@csphoenix1 : There are similar issues: #33 #160

Your suggested methods are possible only through the cooperation of a usbip server.

**Comment by csphoenix1** [comment]
Thank Cezanne. I will check that :)

**Comment by cezanne** [comment]
@csphoenix1 : Please, check [this](https://github.com/cezanne/usbip-win/wiki/Deployment-Tips#handling-abortive-disconnection).
