### ISSUE TITLE
ERROR: Open VHCI driver

### ISSUE THREAD

**Issue by ImLorio** [cezanne/usbip-win#215]
I am using usbip to connect my laser engraver, last week everything worked.
Today when I wanted to reconnect my engraver laser, and I got an error.

Error:
![image](https://user-images.githubusercontent.com/67203548/102919147-9f131100-4488-11eb-9a71-8ca14dd99de4.png)

I go in device manager and I have this:
![image](https://user-images.githubusercontent.com/67203548/102919235-c8cc3800-4488-11eb-9b6a-4ebe8d20d038.png)
![image](https://user-images.githubusercontent.com/67203548/102919814-d3d39800-4489-11eb-978b-667050f224ab.png)

Who can help me please ? (and sorry for my english, i'm french --')

**Comment by cezanne** [comment]
@ImLorio : Did you enable test signing? You said it was working last week, so I suspect that test singing was disabled by something.

**Comment by ImLorio** [comment]
I don't know, I followed the readme tutorial

**Comment by cezanne** [comment]
@ImLorio : You can check if test signing is enabled such as the below image. Type `bcdedit` in a command window. If enabled, a "Test Mode" watermark is displayed at the left bottom corner of a screen. 

![testsigning_capture](https://user-images.githubusercontent.com/242044/103504463-d0350d80-4e9a-11eb-9b2a-6800355642d8.png)

**Comment by cezanne** [comment]
@ImLorio : I found a good youtube tutorial. Please refer: https://github.com/cezanne/usbip-win/issues/64#issuecomment-753598810

**Comment by cezanne** [comment]
@ImLorio : I'll close this issue. Please reopen if you want.
