### ISSUE TITLE
Invalid Argument over \driver \usbip test.pfx

### ISSUE THREAD

**Issue by Steveo10** [cezanne/usbip-win#225]
Hello

I have tried to compile the project and I get the following error :

invalid argument <.. \ driver \ usbip test.pfx> for property <test certificate>

I have read that the key is placed and then it is modified with 2 points but I keep getting the same error

Will I have the certificate damaged or bad?

![image](https://user-images.githubusercontent.com/79330222/109198232-98906680-7763-11eb-8786-143db959dffc.png)

**Comment by cezanne** [comment]
@Steveo10 : Did you check the relative path? `..\usbip_test.pfx` seems to be a correct path.

**Comment by Steveo10** [comment]
hi @cezanne yes


I have checked the path and made the changes but I always get an error in usbip_vhci and usbip_vhci_ude.

I have placed the same path in the usbip_stub and there I have no error code.

I leave you a picture of the new error, any other recommendation that you can help me with?

![Error 2](https://user-images.githubusercontent.com/79330222/109534916-807d5780-7a81-11eb-946e-c279dbc80aa2.PNG)

**Comment by cezanne** [comment]
@Steveo10 : Well, I believe that build has no problem even though you don't care a test certificate path.
If you did not intend to use an alternate path or another certificate, please remove `driver/vhci/usbip_vhci.vcxproj.user` and try to build again. Certificate setting will be reverted to a usbip-win repository version by removing that file.

**Comment by cezanne** [comment]
@Steveo10 : I'll close this issue. Please reopen if you need.
