### ISSUE TITLE
Add information about pnputil to README to help fix binding issues

### ISSUE THREAD

**Issue by chunky125** [cezanne/usbip-win#228]
I had some issues with binding and unbinding with usbip, meaning that I ended up with usbip-stub driver overriding some devices which I did not want it to.

I used pnputil -d oemXXX.inf to fix this, and I think that it is worth adding this to your README to help people who might have the same issue in future, especially while development is ongoing.

**Comment by cezanne** [comment]
@chunky125 : Great! Could you submit a PR about your changed README ?

**Comment by cezanne** [comment]
@chunky125 : I'm going to close this issue. Please reopen if you need.

**Comment by amanvats88** [comment]
For all those who stumbled here looking for a quick fix to **unbind** USB device, refer to #271.
