### ISSUE TITLE
Who are you, why do you maintain this project, and how are you funded?

### ISSUE THREAD

**Issue by R030t1** [cezanne/usbip-win#229]
Hello maintainer, I appreciate your work. Do you think you could add these things to README?

**Comment by cezanne** [comment]
@R030t1 : 
> Hello maintainer, I appreciate your work. Do you think you could add these things to README?

The first and second are not adequate to README. 
The fund acknowledgement has been already mentioned at the tail of README.

**Comment by R030t1** [comment]
Apologies for my oversight, I see the notice at the end. It is sufficient.
I asked for these things as they are helpful when evaluating the quality of a project, the motives of its authors, and the likelihood that it will remain maintained. The notice does all of these for now.
