### ISSUE TITLE
Request for review for a qt ui interface

### ISSUE THREAD

**Issue by dicetrash** [cezanne/usbip-win#233]
I was able to get qtusbip project, a small web interface that runs ontop of usbip to work as a windows client
https://github.com/dicetrash/usbip-win/tree/master/userspace/src
some of the release is sort of weird but all in all it works as expected with a qusbip server (which is usbip with added group search capability)

**Comment by cezanne** [comment]
@dicetrash : Now, it's a time that a nice GUI frontend is need for usbip-win. I've never really thought about using QT, but could you please it as a PR?

**Comment by cezanne** [comment]
@dicetrash : Close this issue. Please reopen if you need.
