### ISSUE TITLE
usbip: error: vhci driver is not loaded

### ISSUE THREAD

**Issue by zengshing** [cezanne/usbip-win#235]
I have a question when I attached a USB device in Windows 10.
![图片](https://user-images.githubusercontent.com/39617342/114399051-1523bb00-9bd3-11eb-9426-4a5ca17537c4.png)

**Comment by Zerowalker** [comment]
same issue here, the drivers install fine as far as i can tell.

**Comment by Zerowalker** [comment]
Okay it might be the TESTSIGNING, thought i didn't need it as i installed the drivers just fine.
But tried using it on a virtual machine and when i set it to ON it seems to make the driver load.
Kinda odd though, i thought it only mattered for actually installing it?

**Comment by cezanne** [comment]
@zengshing : As @Zerowalker pointed out, you might not run `bcdedit /set TESTSIGNING ON`. In that case, such the error message is generated even though `usbip_test.pfx` has been already installed.
