### ISSUE TITLE
Why can't I find the USBPcap interface for it in Wireshark?

### ISSUE THREAD

**Issue by matallui** [cezanne/usbip-win#236]
Hi! I'm trying to use Wireshark to capture the USB traffic going through the virtual hub created by the driver on the Windows client side. However, I don't seem to be able to find it.

Am I missing something? Is this something that's not supposed to work for some reason?

**Comment by cezanne** [comment]
@matallui : Maybe, a vhci device cannot be captured by USBPcap.

Close this issue.
