### ISSUE TITLE
FlashPro 6 device not binding

### ISSUE THREAD

**Issue by rkhat2** [cezanne/usbip-win#239]
I have a [polarfire SoC FPGA](https://www.microsemi.com/product-directory/soc-fpgas/5498-polarfire-soc-fpga). One of the USB ports on it uses [Flashpro 6](https://www.microsemi.com/product-directory/programming-and-debug/4977-flashpro#device-support).

When I try to bind it in usbip-win server, I get:

```
usbip: error: failed to bind device on busid 1-189 
```

The same USB works with a usbip server in Linux and works with VirtualHere in Windows. Other USBs work fine in usbip-win server. Any reason why this one doesn't work?

I would also like to point out that it shows in Linux as /dev/hidrawN where N is a number. Is hidraw not supported?

**Comment by cezanne** [comment]
@rkhat2 : 
> The same USB works with a usbip server in Linux and works with VirtualHere in Windows. Other USBs work fine in usbip-win server. Any reason why this one doesn't work?

usbip-win server (aka stub) still has many issues. `usbip.exe --debug bind -b 1-189` will provide more useful information to resolve your issue.

**Comment by cezanne** [comment]
@rkhat2 : Any progress? I'll close this issue. Please reopen if you need.
