### ISSUE TITLE
usbip: error: failed to unbind device on busid 1-121

### ISSUE THREAD

**Issue by mreyesATS** [cezanne/usbip-win#243]
Dear all,

I am trying to unbind a device I have binded using usbip-win but I get this error:

`C:\Users\mreyes\Desktop\usbip_server>usbip.exe unbind -b 1-121
usbip: error: failed to unbind device on busid 1-121`

I tried in another computer and it performances perfectly so I was wondering if any of you could have an idea of what could be going on.

I've seen there [was a reported issue of March 2020](https://github.com/cezanne/usbip-win/issues/110). I used the patched usbip.exe file and I got this:

`PS C:\Users\mreyes\Desktop\usbip_server> .\usbip.exe unbind -b 1-121
usbip: error: failed to rollback driver: 259
usbip: error: failed to unbind device`

I don't understand what is going on. Does any of you have an idea of what can be wrong?

**Comment by harryyue** [comment]
Hi

Does this error have been solved?
I use release usbip-win-0.3.5-dev, and follow "Install" ,when I run “usbip.exe bind -b 1-122”，I also get this error.
