### ISSUE TITLE
Debug Assertion Failed when listing USB Devices

### ISSUE THREAD

**Issue by KKonaOG** [cezanne/usbip-win#246]
Using version 0.3.5(dev) on Windows 10 Build 21390 (Insiders), the following error appears:

![image](https://user-images.githubusercontent.com/38236274/123559339-1049be80-d761-11eb-8b5f-4deaa0868a98.png)

Clicking Retry will sometimes get the system to print USB devices, sometimes it just falls through with no output.

**Comment by KylerFarrar** [comment]
Small update, clicking ignore will allow it to output devices. Retry does not allow it to continue.

**Comment by Ithilien** [comment]
Im not sure if this is a problem with the release or just our download of it; but its a result of corruption [userspace/usb.ids](https://github.com/cezanne/usbip-win/blob/master/userspace/usb.ids); if you replace the contents of that file on your machine with that in the repo, it should resolve the issue. I had the same problem and after replacing my local usb.ids with the one actually in the repo; it didnt have this assertion failure any more.

**Comment by cezanne** [comment]
@KKonaOG : I had uploaded the corrupted usb.ids, which was replaced with a fixed one.
