### ISSUE TITLE
UDE Driver is not support android bootloader (fastboot device)

### ISSUE THREAD

**Issue by dYongb** [cezanne/usbip-win#269]
Hello, 

1. ude driver is not support android bootloader (fastboot), but wdm driver is support it...
2. wdm driver is not support multi config usb device. (e.g. LAN2USB embeded driver device)

Could you check it please ?

**Comment by cezanne** [comment]
@dYongb : There's no such USB device in my hand. USB packet captured logs would be helpful to resolve your issue. Cloud you try [USBPCap](https://desowin.org/usbpcap/)? It is a cool stuff to capture USB packets.

I'll close this issue. Please reopen if you need.
