### ISSUE TITLE
The system can't occupy the Hid-Complaint device

### ISSUE THREAD

**Issue by ChunHuCui** [cezanne/usbip-win#270]
Hi, there.
I tried to redirect the pen input device(HID-Compliant device). The device is plugged on the stub side, and the pen input device is displayed on the client's device manager.
but if I connect to the client computer using the mstsc, then can't see the redirected pen input device's cursor.
(I can see the cursor point outside of the host's locking screen).
Could you possibly let me know did you ever check this HID-Compliant device on USBIP?

Thank you.

**Comment by cezanne** [comment]
@ChunHuCui : 
RDP(mstsc) uses another virtual pointing device than devices attached to the console desktop. It's right that there was no pen input device in the remote desktop session.

Close this issue.
