### ISSUE TITLE
How to remove USB/IP STUB from Device

### ISSUE THREAD

**Issue by mx0c** [cezanne/usbip-win#278]
After Binding a USB License Dongle with USB/IP-Win i can't use it anymore. I tried unbinding it via CLI but it failed. I also uninstalled the used VHCI Driver via CLI. How do i remove the installed drivers for this Device (USB/IP STUB) ?

https://i.stack.imgur.com/zcQrA.png

**Comment by cezanne** [comment]
@mx0c: What's the error message ?  Your comment would improve usbip-win.

If usbip.exe cannot unbind, you can uninstall a stub driver in device manager. Be sure the "Delete the driver software for this device" checkbox to be selected.

![remove_stub](https://user-images.githubusercontent.com/242044/137624329-cd754bf3-0f73-4a26-8876-5110c8256ab1.png)
