### ISSUE TITLE
ip adress

### ISSUE THREAD

**Issue by peleroform** [cezanne/usbip-win#288]
to attach the device the ip of the server is need to integrte in usbip.exe attach -r <IP> -b 2-2

situation:

server - where the USB device is installed local
client - where the USB device should be used virtuell

server build a connection with VPN to network of client.
client is used from server with RDP

How will the used IP found out?

**Comment by Aussiedler** [comment]
on your router web interface ....

**Comment by cezanne** [comment]
@peleroform : Did you mean to know the server IP?
Close this old issue. Please reopen if you need.
