### ISSUE TITLE
usbip: error: failed to connect a remote host: 192.168.xxx.xxx

### ISSUE THREAD

**Issue by Aussiedler** [cezanne/usbip-win#293]
Hello @all!

First of all I would like to say big thx for the possibility to bind usb devices through the ethernet!
Thanks to spent your time to read my problems.

I would try usbip with an raspberry pi 3b and a windows 11 vm client with a space mouse navigator usb device.

On the raspberry side I would get all to work:

<img width="696" alt="Bildschirmfoto 2021-12-20 um 22 17 36" src="https://user-images.githubusercontent.com/403109/146834003-ae1d5c9e-057b-4422-9786-4d8304fba519.png">

On the win client I got at the beginning probs to install the certificate, because I done it like in a YouTube video where the guy paste the certificate only one time and in the default path. After reading carefully the install instruction here on git I were able to install it and the driver:

![Bildschirmfoto 2021-12-20 um 22 21 32](https://user-images.githubusercontent.com/403109/146834460-2600bdfc-73ea-4834-9fb5-bb73063591c5.png)

But after that I can't bind the device on he client. every time I get the error:

usbip: error: failed to connect a remote host: 192.168.10.58

Both the raspberry and the win client are in the same network and available. I don't know what is going on here...

![Bildschirmfoto 2021-12-20 um 22 21 19](https://user-images.githubusercontent.com/403109/146834425-e249f8f2-faa7-4d7b-bb02-61734a936f1e.png)

Can you guys please help me.

//EDIT:  Furthermore I have to add.... I'm not a raspy pro... I configured it to work with wifi and let the rest of the setting to default. It is the latest raspbian lite image... should I have to configure something more on the device?

//EDIT2: I tested ou with an second notebook with a native windows 11 installation with the same result...

//EDIT3: I fixed it. The solution was a tipping mistake. Instead of "sudo mod probe usbip-host" it should be "sudo mod probe usbip_host" and after that starting the deamon on the raspberry is required with "sudo usbipd"

After that I can connect to the pi and attach the device

** can be closed **

**Comment by cezanne** [comment]
@Aussiedler :  Nice work. I'll close this issue.
