### ISSUE TITLE
powershell not working

### ISSUE THREAD

**Issue by TIYYA** [cezanne/usbip-win#295]
powershell not working .
 i try ./usbip.exe on powershell.
 cmd open and cmd automatic closed

**Comment by cezanne** [comment]
@TIYYA : usbip.exe works under both Powershell and CMD. 

>  cmd open and cmd automatic closed

Maybe, you executed in non-administrator mode. You will get a command output if a powershell window run with administrator privilege.
I'll close this issue. Please reopen if you need.
