### ISSUE TITLE
vhci driver is not loaded for signed drivers

### ISSUE THREAD

**Issue by knavels** [cezanne/usbip-win#296]
We've asked our client to sign the driver and we installed the driver properly but I still get `vhci driver is not loaded` error when I want to attach a new device, any experience about this?

**Comment by vadimgrn** [comment]
Try this build
https://github.com/vadimgrn/usbip-win/releases

**Comment by knavels** [comment]
@vadimgrn I'm glad that I know there is a repo with active development for windows client part, I tested your build unfortunately it didn't help, I checked the Driver though it is signed and in the Driver tab (Device manager, Properties submenu from context menu for the installed driver), it shows the Signature data, but in the General tab it says that: `Windows cannot verify the digital signature for the drivers required for this device. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source. (Code 52)`

**Comment by vadimgrn** [comment]
@knavels [knavels](https://github.com/knavels) Thank you for your feedback! Indeed I haven't change code that installs drivers, but vhci driver itself is improved significantly.

**Comment by cezanne** [comment]
@knavels : close this issue. Please reopen if you need.
