### ISSUE TITLE
What happens if you don't uninstall USBIP driver (client side) before disabling Test Mode?

### ISSUE THREAD

**Issue by e-t-l** [cezanne/usbip-win#300]
In other words, what happens if you install the driver with usbip.exe, then when you're done, you skip the step `PS> usbip.exe uninstall` and go directly to `bcdedit.exe /set TESTSIGNING OFF`? Will Windows throw an error? Blue screen? Fail to disable testsigning?

**Comment by Ranhuiryan** [comment]
System won't break, but you can't use the driver either. Switching back to test mode the drive would work again.
