### ISSUE TITLE
vhci driver weird code

### ISSUE THREAD

**Issue by Kogotoro** [cezanne/usbip-win#322]
/driver/vhci/vhci_devconf.c
function setup_intf(...)
`
intf->InterfaceHandle = TO_INTF_HANDLE(intf->InterfaceNumber, intf->AlternateSetting);
`
considering what 
`
#define TO_INTF_HANDLE(intf_num, altsetting)	((USBD_INTERFACE_HANDLE)((intf_num << 8) + altsetting))
`
and 
`intf->InterfaceNumber, intf->AlternateSetting` both UCHAR (ie 8bits and there 8 bits left shift on first of them?)

its eq to
`
intf->InterfaceHandle = (USBD_INTERFACE_HANDLE)(intf->AlternateSetting);
`
???

**Comment by vadimgrn** [comment]
If you really want to improve usbip client, consider this [project](https://github.com/vadimgrn/usbip-win2/tree). This project is stagnating.

**Comment by vadimgrn** [comment]
The author was working on UDE driver, so VHCI driver is double abandoned.

**Comment by vadimgrn** [comment]
Regarding your question, read about integral promotions in C.

**Comment by Kogotoro** [comment]
> Regarding your question, read about integral promotions in C. In expression intf_num << 8 a compiler promotes UCHAR to int and does shift.

thx
