### ISSUE TITLE
usbip-win fails to run on wine

### ISSUE THREAD

**Issue by schloegl** [cezanne/usbip-win#329]
I'm trying to use an usbip client for windows on wine. Unfortunately, it fails to install and run [[1](https://appdb.winehq.org/objectManager.php?sClass=application&iId=20441)]. Do you have any plans to make it work on Wine ?

**Comment by phlplowe9** [comment]
what's the purpose of running usbip-win under wine vs the native linux version of usbip?

**Comment by schloegl** [comment]
In the past usbip on the host was not working, in more recent version of wine (e.g. wine 8.x) this does not seem to be an issue anymore. At this time, I'm not aware of a use case where host-based usbip would not work. 

This issue can be closed.
