### ISSUE TITLE
UsbIp.exe 0.0.6 (client side) not working on windows 2012 r2 ?

### ISSUE THREAD

**Issue by Eric-N-Be** [cezanne/usbip-win#57]
hi,
i just try to use usb-ip (0.0.6) for windows (server and client) it's working great with win 2019 (server side) and win 10 (1903)

(usbip: info: received request: 0x8003
usbip: debug: C:\work\usbip-win\userspace\src\usbipd\usbipd_import.c:18:[forwarder_stub] stub forwarding started
usbip: debug: C:\work\usbip-win\userspace\src\usbipd\usbipd_import.c:108:[recv_request_import] import request busid 1-140: complete
usbip: info: request 0x8003: complete)

 but i f i make the same configuration for the client on a windows 2012r2 it's not working ...
the drivers are not correctly installed
(device status : Windows cannot initialize the device driver for this hardware. (Code 37)
{Wrong Type}
There is a mismatch between the type of object required by the requested operation and the type of object that is specified in the request.)
then of course the usbip command does not working....

i see this post drivers (version 0.0.3) => usbip_vhci not loading on Windows 7 #12 it's solve my drivers problem but i don't have the lastest drivers...

**Comment by cezuni** [comment]
@Eric-N-Be : Here is a vhci driver for windows 7(x64): [vhci_win7.zip](https://github.com/cezuni/usbip-win/files/3452130/vhci_win7.zip)
This is built from update-to-date master branch 35b0c116734957a6d0a4cde217b09a45a0593bd8. (No test for the driver is done)
