### ISSUE TITLE
usbip error:failed to update driver:103

### ISSUE THREAD

**Issue by zhLoser01** [cezanne/usbip-win#60]
I use win7 as the server side.
![1565057191(1)](https://user-images.githubusercontent.com/23304686/62506145-04357a80-b832-11e9-9cc4-78411b1f3e4e.jpg)

**Comment by cezuni** [comment]
@zhLoser01 : The error(0x103, ERROR_NO_MORE_ITEMS) in your screenshot may indicate that your system has a more specific driver than usbip_stub.sys in a temporarily generated inf. Take a look at [UpdateDriverForPlugAndPlayDevices API in msdn](https://docs.microsoft.com/en-us/windows/win32/api/newdev/nf-newdev-updatedriverforplugandplaydevicesa). According to the document, the following code may require additional INSTALLFLAG_FORCE  flag. Can you try?  
https://github.com/cezuni/usbip-win/blob/f87ff13c0bef32062a016d6e6d0a3b8f3619ce56/userspace/lib/usbip_stub.c#L176

**Comment by zhLoser01** [comment]
![image](https://user-images.githubusercontent.com/23304686/62588913-0d8a1a00-b8fa-11e9-874b-178f338a6b76.png)
What should I do?

**Comment by cezuni** [comment]
@zhLoser01 : modify the source as follows:
 "INSTALLFLAG_NONINTERACTIVE" -> "INSTALLFLAG_NONINTERACTIVE | INSTALLFLAG_FORCE"

**Comment by zhLoser01** [comment]
![image](https://user-images.githubusercontent.com/23304686/62592156-ade53c00-b904-11e9-9a11-541986069c57.png)
![image](https://user-images.githubusercontent.com/23304686/62592165-bfc6df00-b904-11e9-92dc-268f9f0184cd.png)

**Comment by zhLoser01** [comment]
error 103

**Comment by cezuni** [comment]
@zhLoser01 : Which drivers are currently loaded for the DataTraveler G4 device ? You can manually replace the driver with an usbip stub driver via device manager.

**Comment by zhLoser01** [comment]
![image](https://user-images.githubusercontent.com/23304686/62598281-7930af00-b91b-11e9-9fe5-f0b31ba21a92.png)
I manually added this driver

**Comment by zhLoser01** [comment]
![image](https://user-images.githubusercontent.com/23304686/62598598-7da99780-b91c-11e9-9954-c6825c2a5701.png)
I have manually updated the driver

**Comment by cezuni** [comment]
@zhLoser01 : If you can update the driver manually, there's no reason to fail with usbip bind. Can you try with usbip bind again after removing the device?

**Comment by cezuni** [comment]
@zhLoser01 : I recommend you to build usbip.exe with no INSTALLFLAG_NONINTERACTIVE. If that flag is dropped, some useful window may appear.

**Comment by zhLoser01** [comment]
![image](https://user-images.githubusercontent.com/23304686/62599782-bac35900-b91f-11e9-837e-b62441a1239b.png)
This file is generated by you, how can I generate it?

**Comment by cezuni** [comment]
@zhLoser01 : It's a template file for a stub driver inf. You can get it from [source tree](https://github.com/cezuni/usbip-win/blob/master/driver/stub/usbip_stub.inx) or [release page](https://github.com/cezuni/usbip-win/releases/download/v0.0.5/usbip_stub.inx).

**Comment by zhLoser01** [comment]
Yes, I use the source code you posted, but you are 64-bit, my server is 32-bit.

**Comment by cezuni** [comment]
@zhLoser01 : Well, usbip-win is not ready for 32bit. But you can easily edit the file for 32bit. Maybe  all most things to do is to replace amd64 -> x86 ??

**Comment by zhLoser01** [comment]
![image](https://user-images.githubusercontent.com/23304686/62600864-84d3a400-b922-11e9-8a73-8174eb53a574.png)
Yes, I am compiling with x86, the compiler can pass, but I don't know why the binding failed. The error code is 103.

**Comment by cezuni** [comment]
@zhLoser01 : usbip_stub.inx should be properly modified for 32bit(x86). Did you edit that file?

**Comment by zhLoser01** [comment]
no

**Comment by cezuni** [comment]
> no

You should. If you have trouble for editing, I'll do that later..

**Comment by zhLoser01** [comment]
![image](https://user-images.githubusercontent.com/23304686/62601386-d3ce0900-b923-11e9-83f6-15370bbf8044.png)
I don't know how to compile this file.

**Comment by cezuni** [comment]
@zhLoser01 : usbip_stub.inx is just a simple text file. usbip.exe reads that file and automatically generates a stub driver installation file(inf). No need to compile.

**Comment by zhLoser01** [comment]
![image](https://user-images.githubusercontent.com/23304686/62601735-a6358f80-b924-11e9-9d3c-dab15d4aca94.png)
Ok, compiling this usbip_stub with x86 is also successful.

**Comment by zhLoser01** [comment]
![image](https://user-images.githubusercontent.com/23304686/62602399-3cb68080-b926-11e9-92e2-670cc8526312.png)
![image](https://user-images.githubusercontent.com/23304686/62602410-47711580-b926-11e9-8a8b-88f6b66d8714.png)
I commented out this paragraph. Is this a hint that the binding is successful?

**Comment by cezuni** [comment]
@zhLoser01 : No, it's not working. You just need a modified usbip_stub.inx for 32bit.

**Comment by zhLoser01** [comment]
![image](https://user-images.githubusercontent.com/23304686/62603253-1d205780-b928-11e9-9326-0f9f785539d6.png)
I don't know how to change this to 32-bit.

**Comment by cezuni** [comment]
@zhLoser01 : I'm not sure but all you have to do is to replace amd64 with x86 for usbip_stub.inx file. Here is [good reference](https://docs.microsoft.com/ko-kr/windows-hardware/drivers/install/inf-manufacturer-section).

**Comment by zhLoser01** [comment]
So, this usbip_stub.inx file needs to be written manually, it is not automatically generated？

**Comment by zhLoser01** [comment]
![QQ图片20190808114651](https://user-images.githubusercontent.com/23304686/62673778-4c8b9e80-b9d2-11e9-8bb4-f75e358568ce.png)
@cezuni What is the cause of this error?

**Comment by cezuni** [comment]
> So, this usbip_stub.inx file needs to be written manually, it is not automatically generated？

No, it's not automatically generated. You can edit the file manually.

The server screenshot tells that the 1-71 device is not correctly bound to a usbip stub. Please retry after you edits the usbip_stub.inx.

Here is a [modified usbip_stub.inx for x86](https://github.com/cezuni/usbip-win/files/3480060/usbip_stub.inx.zip), which is not tested because I have no x86 test machine.

**Comment by zhLoser01** [comment]
The server uses 32 bits and the client uses 64 bits. This seems to be no good

**Comment by cezanne** [comment]
@zhLoser01 : Close too old issue.
