### ISSUE TITLE
Win7 as USBIP Client and Server

### ISSUE THREAD

**Issue by XT19958** [cezanne/usbip-win#68]
Hello！I am configuring my windows 7 as client and server using this repository. I bind a USB flash drive on server,client connect server successful. And the device driver runs normally,but the client recognized the USB flash drive as a hard disk，and can't open it ,What is the reason for this?
![F0 BC7}LXDL9Q~ N00{8D}E](https://user-images.githubusercontent.com/51979365/65217472-b8d7e280-dae6-11e9-85c1-6cffa136f9fc.png)
![87SKNJ26W0SK_X{ }0XDJJE](https://user-images.githubusercontent.com/51979365/65217498-c55c3b00-dae6-11e9-95e2-d58d1ac66416.png)

**Comment by cezuni** [comment]
@XT19958 : A USB flash drive is one of the working good devices with usbip-win. How about trying another USB device such as a USB mouse? It is also a working good device.

**Comment by XT19958** [comment]
@cezuni : Thanks for your reply！My problem will happen only when **Win7** bind a USB flash drive as server（Win10 works good）.

**Comment by cezanne** [comment]
@XT19958 : Close too old issue. Please reopen if you want.
