### ISSUE TITLE
Flash drive is not working

### ISSUE THREAD

**Issue by kmvi-dev** [cezanne/usbip-win#70]
@cezuni ,you can help me?
I am using the last version from the repository https://github.com/cezuni/usbip-win
The server part is deployed on 4.18.0-25 @26~18.04.1-Ubuntu SMP using usbutils from the distribution.
The client part is deployed on the VmWare virtual machine in the Windows 10 Pro (x64), in which debug mode is enabled.
The virtual machine is deployed on a host with a Windows 10 Pro (x64).
After building the client part, the usbip module and the driver were copied to the guest station.
Further, all actions were carried out according to the Readme.

As a result of buid and testing the assembly, it turned out the following:

Flash drive on Linux station [server side usb / ip]
![Flash_drive-test](https://user-images.githubusercontent.com/48018001/65788126-157c7280-e163-11e9-892c-2dafebf5467d.jpg)

Mass storage device on windows usb/ip-client

![issue-1](https://user-images.githubusercontent.com/48018001/65788705-51fc9e00-e164-11e9-82e3-4c3b3f4f03b9.jpg)

![issue-2](https://user-images.githubusercontent.com/48018001/65788709-5628bb80-e164-11e9-89c2-609e7f181583.jpg)

![issue-3](https://user-images.githubusercontent.com/48018001/65788714-588b1580-e164-11e9-9f12-d1d2431a1ac4.jpg)

## in vhci_write.c 
static NTSTATUS  store_urb_iso(PURB urb, struct usbip_header *hdr)...
hdr->u.ret_submit.status = 0xFFFFFFE0 ;
urb-> UrbHeader.Status = USBD_STATUS_STALL_PID;
![изображение](https://user-images.githubusercontent.com/48018001/65851154-8cc82700-e35a-11e9-92e4-51959bb69bff.png)
##
Before describing the problem I acquainted myself with issues #6 ,#7 ,#22, but I did not find a solution of my problem in them . I did not also find any advice how I should localize the problem.
The archive contains screenshots, *.evtx file (windows event log) of issues with  flash drive and kernel debug lines
**[ussues.zip](https://github.com/cezuni/usbip-win/files/3663942/ussues.zip)
[logs-usbip(win-lin).zip](https://github.com/cezuni/usbip-win/files/3664368/logs-usbip.win-lin.zip)**

**Comment by cezuni** [comment]
@kmvi-dev : 
In flashdrive.LOG(usbip-win vhci log), there's no suspicious line except for this.
```
00000244	22:57:52.184	usbip_vhci: vpdo: minor: IRP_MN_REMOVE_DEVICE, IRP: 0xFFFFD00800E05010
```

From that line, the vhci device seems to have been removed by an upper driver.
Is there any such a driver in your Windows VM ?

**Comment by kmvi-dev** [comment]
@cezuni 
No . I removed all the system USB drivers from the virtual machine before booting Windows.
I want to note that forwarding does not work correctly with some devices from the manufacturer Alcor Micro Corp.
 I found two such devices for the test. A flash drive and a card reader. The rest of the devices that I used in my projects work quite correctly
 ( Thank you for responding ) .

**Comment by cezanne** [comment]
@kmvi-dev : Sorry for my late response. Any progress on this closed issue?

**Comment by kmvi-dev** [comment]
@cezuni 
Yes ,the flash drive turned out to be malfunctioning. :).
But there is another problem. This is due to card readers.
If all card reader slots are filled with SD cards, then a card reader is available and SD cards are read.
But if at least one slot is free, then transferring a card reader is not possible.
Card readers in working condition.

**Comment by kmvi-dev** [comment]
@cezuni  
Open a new topic on this issue?

**Comment by cezanne** [comment]
@kmvi-dev : 
> Open a new topic on this issue?

Yes, it can be a new topic.

**Comment by kmvi-dev** [comment]
@cezuni 
Well, today I’ll try to collect debug information and create a new topic for this issue.

**Comment by kmvi-dev** [comment]
@cezuni 
I checked the latest version from the repository and did not find any problems with the card reader. Everything works. Thank you for participating in solving problems with my devices.
P.S 
I needed to update the driver version and the last question would not be :)
