### ISSUE TITLE
usbip: error: recv op_common;usbip:error:failed to read:err:6

### ISSUE THREAD

**Issue by zhLoser01** [cezanne/usbip-win#72]

**Comment by zhLoser01** [comment]
Must I use the v142 generation tool?  @cezuni

**Comment by zhLoser01** [comment]
![1571033995(1)](https://user-images.githubusercontent.com/23304686/66732263-c6864b00-ee8d-11e9-9fa1-e1d9a34bb5f7.jpg)

**Comment by zhLoser01** [comment]
![1571035667(1)](https://user-images.githubusercontent.com/23304686/66733296-a9ec1200-ee91-11e9-9876-b972442fb8a2.jpg)

**Comment by zhLoser01** [comment]
![1571107638(1)](https://user-images.githubusercontent.com/23304686/66796101-38679e80-ef39-11e9-8bd1-205ac838e23e.jpg)

**Comment by zhLoser01** [comment]
![1571107676(1)](https://user-images.githubusercontent.com/23304686/66796127-533a1300-ef39-11e9-8818-795b2c0d1176.png)

**Comment by zhLoser01** [comment]
![1571119689(1)](https://user-images.githubusercontent.com/23304686/66804534-44f9f000-ef55-11e9-8241-f7eda163a091.png)

**Comment by zhLoser01** [comment]
![1571119751(1)](https://user-images.githubusercontent.com/23304686/66804587-6ce95380-ef55-11e9-9b12-01080bc2c381.png)

**Comment by zhLoser01** [comment]
Can list usb devices

**Comment by zhLoser01** [comment]
![1571219130(1)](https://user-images.githubusercontent.com/23304686/66907943-d001e580-f03c-11e9-8294-fc0c7057ec51.png)

**Comment by cezanne** [comment]
@zhLoser01 : Close too old issue. Please reopen if you want.

**Comment by orcuan** [comment]
Any updates on this issue ? It is still relevant for me.

**Comment by designworxz** [comment]
Still getting this error with new release
usbip: error: recv op_common
usbip: error: read_devbuff: failed to read: err: 0x6

**Comment by koudis** [comment]
Hi,

0x6 is a network error. So you forgot to star usbipd daemon or maybe
firewall?
