### ISSUE TITLE
Is USBb-win running really normal? Is a composite device such as a camera also possible? I have been failing. I don't know who has done the test. Can you tell me? Thank you.

### ISSUE THREAD

**Issue by mankitty** [cezanne/usbip-win#75]
I followed the description of the document, carefully done the relevant tests, windows10 as a client, ubuntu as a server to test, but failed, camera, microphone and other composite equipment can not work, do not know who has succeeded, want to consult Thank you, thank you.

**Comment by zhLoser01** [comment]
Windows does not work, linux can, I have tried the camera successfully

**Comment by kmvi-dev** [comment]
@mankitty  see composite devices #44

**Comment by mankitty** [comment]
thank you,but,this seems can,t to solve my problem.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kmvi-dev"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月25日(星期五) 晚上9:41
收件人:&nbsp;"cezanne/usbip-win"<usbip-win@noreply.github.com&gt;;
抄送:&nbsp;"王灿"<873337054@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [cezanne/usbip-win] Is USBb-win running really normal? Is a composite device such as a camera also possible? I have been failing. I don't know who has done the test. Can you tell me? Thank you. (#75)




@mankitty  see composite devices #44

**Comment by cezanne** [comment]
@mankitty : This issue will be closed. It can be resolved with recent other issues. Please reopen if you want.
