### ISSUE TITLE
Linux -> Windows 10 - BSOD with USB Broadcom device

### ISSUE THREAD

**Issue by calderonth** [cezanne/usbip-win#76]
I am trying to expose a USB device from my Dell laptop with Linux to a Win 10 client (in a VM) using the provided binaries on GitHub.
The setup works with my USB camera but when I try to pass my Broadcom device, Windows crashes immediately with a BSOD.

I have attached the dumpfile created, without the PDB symbols for version 0.0.7 we can't see exactly which function is crashing when analyzing with WinDBG.

[103019-4906-01.zip](https://github.com/cezanne/usbip-win/files/3789126/103019-4906-01.zip)
 
[minidump-analyze-output.txt](https://github.com/cezanne/usbip-win/files/3789125/minidump-analyze-output.txt)

Thanks!

**Comment by cezanne** [comment]
@calderonth : Sorry for too late response. Please retry with a recent version. This issue will be closed. Reopen is always possible but more detailed information is required. Please refer [Reporting Bug](https://github.com/cezanne/usbip-win#reporting-bug).
