### ISSUE TITLE
Is there any way to use the driver without keeping test signing on?

### ISSUE THREAD

**Issue by rzvc** [cezanne/usbip-win#79]
The moment you disable testsigning, you can no longer use the driver.

Is there a way to fix this?

**Comment by koudis** [comment]
No without valid sign.
Driver must be signed and trusted by the system.

You can buy EV Code Sign certificate and sign driver with that cert.

**Comment by MartinDrab** [comment]
> You can buy EV Code Sign certificate and sign driver with that cert.

If you do not mind turning off Secure Boot, no EV certificate is necessary, just standard code signing one (cheaper, easier to obtain).

**Comment by koudis** [comment]
@MartinDrab ou really? I did known that.

So if I understand correctly:

- If the Secure Boost is disabled the normal Code Sign cert is enought even for drivers.
- If the Secure Boost is enabled I need EV Coide Sign cert.

Correct?

**Comment by cezanne** [comment]
I'll close this stale discussion. Please reopen if it is required.
