### ISSUE TITLE
Win10 attach doesn't work(without changing power setting)

### ISSUE THREAD

**Issue by MasterLivens** [cezanne/usbip-win#85]
I'm using WIN10 with version 0.0.5( driver install failure with higher version ), but I could not attach it to the system successfully.
![image](https://user-images.githubusercontent.com/15192583/70406178-d3cd4980-1a7a-11ea-802c-c82876a436d4.png)

**Comment by koudis** [comment]
Hello,

usbip win blocks. It's a feaure :).

Can you try:

- disconnect your usb device from server
- connect your device back to server and bind it to usbip by bind command
- on windows client call usbip.exe list -r
- check that usbip.exe shows right names, device IDs and interfaces of your usb device
- if not try attach your usb device by attach command
- even if attach fail run usbip.exe list -r and check if the device description provided by usbip-win changed

If usbip-win description of the device (from list command) chenged - it can be a problem with device driver update/install (usbip-win does not correctly update HW info etc...).

**Comment by xzcvczx** [comment]
you also might want to change the power settings to disable selectively suspend usb devices. i was having no luck with either of the devices i tried to attach until i changed this setting in win10

<img width="836" alt="Screen Shot 2019-12-21 at 03 00 41" src="https://user-images.githubusercontent.com/2816060/71259871-45bc6180-239e-11ea-9902-8a20e9f6c813.png">

**Comment by koudis** [comment]
@MasterLivens I made some changes in PR #90 . Maybe it helps.

**Comment by cezanne** [comment]
@xzcvczx : 

This project has not treated USB power issue but it's worth to discuss.
  
> i was having no luck with either of the devices i tried to attach until i changed this setting in win10

Did you mean that you were able to attach the device after power setting had been changed?

**Comment by xzcvczx** [comment]
> Did you mean that you were able to attach the device after power setting had been changed?

correct

**Comment by cezanne** [comment]
@xzcvczx : Let me reproduce your case. Please, give your power setting when attach operation failed.

**Comment by cezanne** [comment]
@xzcvczx : It would be todo. Please reopen if you want.
