### ISSUE TITLE
Graphical User Interface for it that supports Windows XP and up

### ISSUE THREAD

**Issue by Zero3K** [cezanne/usbip-win#92]
It would be nice if one could be made.

**Comment by cezanne** [comment]
@Zero3K : Yes, I'm also very eager for a GUI of usbip-win. Close the issue right now but a todo label is assigned.

**Comment by cezanne** [comment]
There's a nice frontend for usbip, which currently supports only linux.

https://github.com/dicetrash/qusbip
https://github.com/dicetrash/qusbipserver
