### ISSUE TITLE
ReactOS support

### ISSUE THREAD

**Issue by Zero3K** [cezanne/usbip-win#93]
Does it support ReactOS as a server and client? If not, then support for it should be added or tell me how to build it for ReactOS.

**Comment by koudis** [comment]
@Zero3K please do not spawn so many issues. Create one feature request issue, make proper description and delete old non-usable issues pls.

**Comment by Zero3K** [comment]
Why?

**Comment by cezanne** [comment]
@Zero3K : Sorry, I have no plan to support ReactOS.
