### ISSUE TITLE
Errors when compiling a debug version of it for 32-bit Windows 7

### ISSUE THREAD

**Issue by Zero3K** [cezanne/usbip-win#94]
I am getting the errors in the attached text file when compiling a debug version of it for 32-bit Windows 7 using Visual Studio 2019 Community Edition:

[usbip-win-windows7-compilation-errors.txt](https://github.com/cezanne/usbip-win/files/4024384/usbip-win-windows7-compilation-errors.txt)

**Comment by koudis** [comment]
PLease delete this issue. It;s diplicited by #95.
