### ISSUE TITLE
Errors when compiling either a debug or release version of it for 32-bit Windows 7

### ISSUE THREAD

**Issue by Zero3K** [cezanne/usbip-win#95]
I am getting the errors in the attached text files when compiling either a debug or release version of it for 32-bit Windows 7 using Visual Studio 2019 Community Edition:

[usbip-win-windows7-x86-release-compilation-errors.txt](https://github.com/cezanne/usbip-win/files/4024394/usbip-win-windows7-x86-release-compilation-errors.txt)

https://github.com/cezanne/usbip-win/files/4024384/usbip-win-windows7-compilation-errors.txt

**Comment by koudis** [comment]
Sorry, we does not support Windows 7. Only windows 10 x64.

**Comment by Zero3K** [comment]
I was able to compile a x64 build for Windows 7 and it works with no issues.

**Comment by koudis** [comment]
Nice, can you close this issue please? :)

**Comment by Zero3K** [comment]
No, another person has managed to get it compiled for a 32-bit OS.

**Comment by koudis** [comment]
Windows 7 is not supported any more. We do not support Windows 7/10 x86 too.

If you want to add support for windows 10 x86, create PR please :)..

**Comment by Zero3K** [comment]
Why is that?

**Comment by Zero3K** [comment]
According to a guy on ReactOS' Mattermost Server, its not able to find the header files.

**Comment by cezanne** [comment]
@Zero3K : x86 build support has been added. Please check 2f82656d80d78f4d186b6bf25be108551c13a67e.
